parameters:
#    agenda_user.example.class: Agenda\UserBundle\Example

services:
#    agenda_user.example:
#        class: %agenda_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
